version: 2
jobs:
  build:
    docker:
      - image: saxtondrey/circleci-node-aws:1.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: build
          command: yarn build
      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rsync -rlpcv --delete -e "ssh -o StrictHostKeyChecking=no" ./dist [user]@[ip]:[dist]
              aws cloudfront create-invalidation --distribution-id [distribution-id] --paths '/*'
            fi 